version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn mock-db
      - run: yarn test
      - run: cd client
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: sudo apt-get update
      - run: sudo apt install -y rsync
      - run: if [ "${CIRCLE_BRANCH}" == "circleci" ] || [ "${CIRCLE_BRANCH}" == "master" ]; then rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '.git*' ./ ubuntu@35.162.65.198:/var/www/cms/hopelab_ayachatbot_cms/; fi
      - run: if [ "${CIRCLE_BRANCH}" == "circleci" ] || [ "${CIRCLE_BRANCH}" == "master" ]; then ssh -o StrictHostKeyChecking=no ubuntu@35.162.65.198 'cd /var/www/cms/hopelab_ayachatbot_cms && yarn install --ignore-optional && cd client && npm i --production && yarn build client && pm2 restart cms'; fi
      - run: if [ "${CIRCLE_BRANCH}" == "staging" ]; then rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '.git*' ./ ubuntu@34.212.32.132:/var/www/cms/hopelab_ayachatbot_cms/; fi
      - run: if [ "${CIRCLE_BRANCH}" == "staging" ]; then ssh -o StrictHostKeyChecking=no ubuntu@34.212.32.132 'cd /var/www/cms/hopelab_ayachatbot_cms && yarn install --ignore-optional && cd client && npm i --production && yarn build client && pm2 restart cms'; fi
      - run: echo "done!"
