version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - run: sudo apt install -y rsync
      #- run: rm yarn.lock
      #- run: yarn install
      #- run: yarn run build
      - run: if [ "${CIRCLE_BRANCH}" == "circleci" ] || [ "${CIRCLE_BRANCH}" == "master" ]; then rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '.git*' ./ ubuntu@35.162.65.198:~/cmsdeploy/; fi
      - run: ssh -o StrictHostKeyChecking=no ubuntu@35.162.65.198 'cd ~/cmsdeploy/ && yarn install'
      - run: echo "done!"
